name: Release
on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build Windows 
        run: "zig build -Dtarget=x86_64-windows -Doptimize=ReleaseSafe -Dexe_name=adl_windows_x86"

      - name: Build Mac_x86 
        run: "zig build -Dtarget=x86_64-macos -Doptimize=ReleaseSafe -Dexe_name=adl_mac_x86"

      - name: Build Mac_ARM 
        run: "zig build -Dtarget=arm-macos -Doptimize=ReleaseSafe -Dexe_name=adl_mac_arm"

      - name: Build Linux_x86 
        run: "zig build -Dtarget=x86_64-linux -Doptimize=ReleaseSafe -Dexe_name=adl_linux_x86"

      - name: Build Linux_ARM
        run: "zig build -Dtarget=arm-linux -Doptimize=ReleaseSafe -Dexe_name=adl_linux_arm"

      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./zig-out/bin/adl_windows_x86
            ./zig-out/bin/adl_mac_x86
            ./zig-out/bin/adl_mac_arm
            ./zig-out/bin/adl_linux_x86
            ./zig-out/bin/adl_linux_arm
            LICENSE

