name: Release
on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Windows 
        run: "deno compile --target x86_64-pc-windows-msvc -o adl_windows_x86 main.ts"

      - name: Build Mac_x86 
        run: "deno compile --target x86_64-apple-darwin -o adl_mac_x86 main.ts"

      - name: Build Mac_ARM 
        run: "deno compile --target aarch64-apple-darwin -o adl_mac_arm main.ts"

      - name: Build Linux_x86 
        run: "deno compile --target x86_64-unknown-linux-gnu -o adl_linux_x86 main.ts"

      - name: Build Linux_ARM
        run: "deno compile --target aarch64-unknown-linux-gnu -o adl_linux_arm main.ts"

      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            adl_windows_x86
            adl_mac_x86
            adl_mac_arm
            adl_linux_x86
            adl_linux_arm
            LICENSE

